### PR TITLE
Tune luajit settings to improve performance

### PR DESCRIPTION
**Pull request by nico-abram**

### CODE REVIEW

**Comment by zeta0134** [comment]
... pardon me while I pick up my jaw off the floor.

**Holy cow.**

This _eliminates_ any trace of lag on my system. I did not even know these settings existed; truthfully, I have not been focused on LuaJIT's minutae. I'm going to play with this a bit and test some more, but I'll probably merge it. I'd like to understand more about _why_ this has such a profound effect, which will be a lovely day filled with blankets, hot chocolate, and a good profiler. I have a hunch it's due to the large number of tiny functions though. LuaGB is a bit of an unusual codebase.

Either way, this lovely stuff. Thank you!

**Comment by nico-abram** [comment]
I had a similar reaction when i tried it on my project :)

I asked about a performance regression in 2.0.5-2.1 in the mailing list and got this as a suggestion. There's a little explanation here: https://www.freelists.org/post/luajit/21-regresion,4

**Comment by lukego** [comment]
We have occasionally bumped these limits on [Snabb](https://github.com/snabbco/snabb). The defaults seem quite conservative. Some programs just do need a big working set of traces and having the limits set too small will cause churning as the JIT recompiles the application over and over again.

The time that you really want to flush the JIT is when your workload changes dramatically. In an emulator that might be when you load a new game, for example, if that will change the behaviour of a lot of your loops. Then it can be beneficial to flush out the old code and recompile. But I'd prefer to call `jit.flush()` in those cases rather than rely on heuristics like "we have lots of code now, so some of it is probably obsolete, so it's probably a good idea to throw it away and compile again."

**Comment by zeta0134** [comment]
Thank you both for the explanations. I'm confident enough about the performance ramifications that I'm comfortable merging this in. I also agree with the idea of flushing the JIT manually when reloading a game, that makes a ton of sense.

For the longest time I've been in kindof a slump with this project, because the performance seemed to be somewhat arbitrary, and profiling results weren't showing any obvious patterns. Even seemingly identical runs of the same game would vary wildly in their performance. I was afraid I'd bumped into either the limit of what LuaJIT could do, or simply my own abilities as a developer. To learn that something so simple was the cause is a _huge_ relief. It also calls into question the results of some of my previous profiling attempts, so I'll need to revisit some of my past ideas.

I need to spend some time re-collecting my thoughts and deciding where to take the codebase from here, (it needs some serious cleanup) but the project has a _future_ again, and for that I can't thank you enough.

**Comment by lukego** [comment]
Glad you see some light at the end of the tunnel :)

I am gradually trying to work out the best way to explain how the JIT works from an application developer perspective. Getting there slowly :). It's not actually so complex but it is very different to a traditional compiler. Finding the right words is hard.

Some resources from my attempts so far at a [blog](https://github.com/lukego/blog/issues) and [YouTube channel](https://www.youtube.com/channel/UC-ATWoBhU7ae5w7s5Rc0sSA). Feedback would be welcome. Once I have all of the bits I hope to find time to weave them into a more coherent whole.

**Pull request merged**
